from django.urls import path
from . import views

urlpatterns = [
    path('', views.home,name='py_home'),
    path('introduction/', views.intro,name='python_intro'),
    path('variables/', views.variables,name='python_var'),
    path('datatypes/', views.datatypes,name='python_dtypes'),
    path('typecast/', views.typecast,name='python_typecast'),
    path('strings/', views.strings,name='python_strings'),
    path('boolean/', views.boolean,name='python_boolean'),
    path('operators/', views.operators,name='python_operators'),
    path('conditional-statement/', views.condstatement,name='python_condstate'),
    path('loops/', views.loops,name='python_loops'),
    path('list/', views.list,name='python_list'),
    path('tuple/', views.tuples,name='python_tuples'),
    path('set/', views.set,name='python_set'),
    path('dict/', views.dict,name='python_dict'),
    path('function/', views.function,name='python_function'),
    path('class/', views.classes,name='python_class'),
    path('inheritance/', views.inheritance,name='python_inheritance'),
    path('polymorphism/', views.polymorphism,name='python_polymorphism'),
    path('scope/', views.scope,name='python_scope'),
    path('modules/', views.modules,name='python_modules'),
    path('exception/', views.exception,name='python_exception'),
    path('filehandling/', views.filehandling,name='python_filehandling'),
    path('json/', views.jsonhandling,name='python_json_handling'),
    path('regex/', views.regex,name='python_regex_handling'),
    path('generators/', views.generators,name='python_generators'),
    path('decorators/', views.decorators,name='python_decorators'),
    path('lambdafnct/', views.lambdafnct,name='python_lambdafnct'),
    path('iterators/', views.iterators,name='python_iterators'),
    path('contextmanager/', views.contextmanager,name='python_contextmanager'),
]
